version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_ENDPOINT=https://61c7-103-135-228-71.ngrok-free.app
      - DB_DSN=host=db user=postgres password=postgres dbname=cookieless_db port=5432 sslmode=disable TimeZone=Asia/Kolkata
  db:
    image: docker.io/bitnami/postgresql:16
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=cookieless_db
    volumes:
      - postgresql_data:/bitnami/postgresql
volumes:
  postgresql_data: